"""files

Revision ID: 7652d4f04bb9
Revises: b330cfccf307
Create Date: 2020-07-21 11:04:17.139261

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7652d4f04bb9'
down_revision = 'b330cfccf307'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('file_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'file_url')
    # ### end Alembic commands ###
